typography_spectrum: 0.9651180487126112
color:
  saturation: 0.8599080943968147
  brandStrength: 1
  rhythmicContrast: 0.9811508189886808
  brandColors:
    - '#101825'
    - '#4B8AD9'
    - '#FFF5D9'
    - '#5B544A'
    - '#AEADAB'
  lightness: 0.3487959706690162
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.7468085
analytics:
  twitter: null
  google: null
  facebook: null
author:
  email: newsbeaconny@gmail.com
  url: newsbeaconny.com
  name: Beacon News
name: BeaconNews
cta:
  bucket: null
  version: null
  domain: null
favicon: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
title: Beacon News
description: The place to find the most current News
purpose: []
